### ISSUE TITLE
建立就失败了 兄弟

### ISSUE THREAD

**Issue by tianweicc** [meicai-fe/mcrn-cli#1]

**Comment by xiongcaichang** [comment]
检查一下 yarn 和 cocoapods安装没有。或者贴个命令行输出呗😅

**Comment by xiongcaichang** [comment]
所需环境
Node
Yarn
CocoaPods

**Comment by Sobranier** [comment]
写到readme里面

**Comment by tianweicc** [comment]
不出意外 环境我应该都有  不过没时间检查了 刚才看见想试试来着 失败了就没仔细看了

**Comment by xiongcaichang** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/10259498/46788790-8584c380-cd6d-11e8-9bcf-1f77a44d1842.png">
哈哈看看属不属于常见问题，已经更新到readme

**Comment by xiongcaichang** [comment]
如果以上不能解决，建议贴出执行错误的输出内容，便于分析原因

**Comment by xiongcaichang** [comment]
closes #1   浏览github发现由于您是Android 开发者， Cocoapods  大概率是未安装的，请先检查环境。由于长时间未收到回复。现将此问题关闭
